## 1. Download dos dados
Fonte: API do InfoDengue, casos semanais de Teresina (2015 - 2026)

In [1]:
import pandas as pd

link = "https://info.dengue.mat.br/api/alertcity?geocode=2211001&disease=dengue&format=csv&ew_start=1&ew_end=53&ey_start=2015&ey_end=2026"
casos_de_dengue = pd.read_csv(link)

In [6]:
casos_de_dengue.to_csv("../data/raw/infodengue_teresina.csv", index=False)

In [2]:
casos_de_dengue.columns

Index(['data_iniSE', 'SE', 'casos_est', 'casos_est_min', 'casos_est_max',
       'casos', 'p_rt1', 'p_inc100k', 'Localidade_id', 'nivel', 'id',
       'versao_modelo', 'municipio_nome', 'Rt', 'pop', 'tempmin', 'umidmax',
       'receptivo', 'transmissao', 'nivel_inc', 'umidmed', 'umidmin',
       'tempmed', 'tempmax', 'casprov', 'casprov_est', 'casprov_est_min',
       'casprov_est_max', 'casconf', 'notif_accum_year'],
      dtype='str')

In [ ]:
# Ultimos casos
casos_de_dengue[["data_iniSE", "casos", "casos_est"]].head(10)

   data_iniSE  casos  casos_est
0  2026-10-04      7       38.0
1  2026-09-27     19       43.0
2  2026-09-20     35       54.0
3  2026-09-13     28       43.0
4  2026-09-06     34       46.0
5  2026-08-30     52       61.0
6  2026-08-23     39       46.0
7  2026-08-16     58       63.0
8  2026-08-09     83       86.0
9  2026-08-02    120      121.0

In [ ]:
# Primeiros casos (2015)
casos_de_dengue[["data_iniSE", "casos", "casos_est"]].tail(10)

     data_iniSE  casos  casos_est
604  2015-03-08    280      280.0
605  2015-03-01    233      233.0
606  2015-02-22    137      137.0
607  2015-02-15     85       85.0
608  2015-02-08     75       75.0
609  2015-02-01     80       80.0
610  2015-01-25     46       46.0
611  2015-01-18     51       51.0
612  2015-01-11     34       34.0
613  2015-01-04     50       50.0

In [11]:
casos_de_dengue.dtypes

data_iniSE              str
SE                    int64
casos_est           float64
casos_est_min         int64
casos_est_max         int64
casos                 int64
p_rt1               float64
p_inc100k           float64
Localidade_id         int64
nivel                 int64
id                    int64
versao_modelo           str
municipio_nome          str
Rt                  float64
pop                   int64
tempmin             float64
umidmax             float64
receptivo           float64
transmissao           int64
nivel_inc             int64
umidmed             float64
umidmin             float64
tempmed             float64
tempmax             float64
casprov               int64
casprov_est         float64
casprov_est_min     float64
casprov_est_max     float64
casconf             float64
notif_accum_year      int64
dtype: object

In [12]:
casos_de_dengue["data_iniSE"].dt.month

AttributeError: Can only use .dt accessor with datetimelike values

In [16]:
casos_de_dengue.shape

(614, 30)

In [17]:
casos_de_dengue.min()

data_iniSE                  2015-01-04
SE                              201501
casos_est                          0.0
casos_est_min                        0
casos_est_max                        0
casos                                0
p_rt1                              0.0
p_inc100k                          0.0
Localidade_id                        0
nivel                                1
id                  221100120150119589
versao_modelo               2023-08-20
municipio_nome                Teresina
Rt                                 0.0
pop                             868075
tempmin                        21.0589
umidmax                      52.661114
receptivo                          0.0
transmissao                          0
nivel_inc                            0
umidmed                      35.663029
umidmin                       18.19422
tempmed                        25.2194
tempmax                      28.346957
casprov                              0
casprov_est                        NaN
casprov_est_min                    NaN
casprov_est_max                    NaN
casconf                            NaN
notif_accum_year                 71033
dtype: object

In [ ]:
casos_de_dengue.max()

data_iniSE                  2026-10-04
SE                              202640
casos_est                       1581.0
casos_est_min                     1581
casos_est_max                     1581
casos                             1581
p_rt1                              1.0
p_inc100k                    182.12712
Localidade_id                        0
nivel                                4
id                  221100120264020741
versao_modelo               2026-10-15
municipio_nome                Teresina
Rt                           16.565691
pop                             868523
tempmin                      25.968329
umidmax                      99.554786
receptivo                          1.0
transmissao                          1
nivel_inc                            2
umidmed                      88.981057
umidmin                      73.769443
tempmed                      31.859157
tempmax                       38.70944
casprov                           1742
casprov_est                        NaN
casprov_est_min                    NaN
casprov_est_max                    NaN
casconf                            NaN
notif_accum_year                 71033
dtype: object

In [23]:
casos_de_dengue.isna().sum()

data_iniSE            0
SE                    0
casos_est             0
casos_est_min         0
casos_est_max         0
casos                 0
p_rt1                 0
p_inc100k             0
Localidade_id         0
nivel                 0
id                    0
versao_modelo         0
municipio_nome        0
Rt                    0
pop                   0
tempmin             442
umidmax             442
receptivo           313
transmissao           0
nivel_inc             0
umidmed             442
umidmin             442
tempmed             442
tempmax             442
casprov               0
casprov_est         614
casprov_est_min     614
casprov_est_max     614
casconf             614
notif_accum_year      0
dtype: int64

In [24]:
casos_de_dengue["diferenca"] = casos_de_dengue["casos_est"] - casos_de_dengue["casos"]
casos_de_dengue[["data_iniSE", "casos", "casos_est", "diferenca"]].head(20)

    data_iniSE  casos  casos_est  diferenca
0   2026-10-04      7       38.0       31.0
1   2026-09-27     19       43.0       24.0
2   2026-09-20     35       54.0       19.0
3   2026-09-13     28       43.0       15.0
4   2026-09-06     34       46.0       12.0
5   2026-08-30     52       61.0        9.0
6   2026-08-23     39       46.0        7.0
7   2026-08-16     58       63.0        5.0
8   2026-08-09     83       86.0        3.0
9   2026-08-02    120      121.0        1.0
10  2026-07-26    146      146.0        0.0
11  2026-07-19    169      169.0        0.0
12  2026-07-12    177      177.0        0.0
13  2026-07-05    259      259.0        0.0
14  2026-06-28    292      292.0        0.0
15  2026-06-21    361      361.0        0.0
16  2026-06-14    631      631.0        0.0
17  2026-06-07    695      695.0        0.0
18  2026-05-31    886      886.0        0.0
19  2026-05-24    849      849.0        0.0